/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomatematicassuma;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author lizar
 */
public class DificultadResta extends javax.swing.JFrame {

    /**
     * Creates new form DificultadResta
     */
    public DificultadResta() {
        initComponents();
        fondo();
        btnPrincipiante.setBackground(Color.white);
        btnInter.setBackground(Color.white);
        btnAva.setBackground(Color.white);
        this.setLocationRelativeTo(null);
        jPanel1.setBackground(Color.white);
    }
    
     public void fondo() {

        //Foto del marco
        ImageIcon marco = new ImageIcon(getClass().getResource("/Imagenes/Pergamino.jpg"));
        Icon marc = new ImageIcon(marco.getImage().getScaledInstance(perga.getWidth(), perga.getHeight(), Image.SCALE_DEFAULT));
        perga.setIcon(marc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrincipiante = new javax.swing.JButton();
        btnAva = new javax.swing.JButton();
        btnInter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        perga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrincipiante.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPrincipiante.setText("Principiante");
        btnPrincipiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrincipianteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrincipianteMouseExited(evt);
            }
        });
        btnPrincipiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipianteActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrincipiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 150, 60));

        btnAva.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAva.setText("Avanzado");
        btnAva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAvaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAvaMouseExited(evt);
            }
        });
        btnAva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAva, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 150, 60));

        btnInter.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnInter.setText("Intermedio");
        btnInter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInterMouseExited(evt);
            }
        });
        btnInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterActionPerformed(evt);
            }
        });
        jPanel1.add(btnInter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 150, 60));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("¡Ahora!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Continuemos con la resta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Selecciona la dificultad...");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        perga.setText("jLabel4");
        jPanel1.add(perga, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -50, 630, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipianteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipianteMouseEntered
        // TODO add your handling code here:
        btnPrincipiante.setBackground(Color.cyan);
    }//GEN-LAST:event_btnPrincipianteMouseEntered

    private void btnPrincipianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipianteActionPerformed

        RestaPrincipiante RP = new RestaPrincipiante();
        RP.setVisible(true);
    }//GEN-LAST:event_btnPrincipianteActionPerformed

    private void btnInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterActionPerformed
        // TODO add your handling code here:
        RestaIntermedio RI = new RestaIntermedio();
        RI.setVisible(true);
    }//GEN-LAST:event_btnInterActionPerformed

    private void btnAvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaActionPerformed
        // TODO add your handling code here:
        
        RestaAvanzado RA = new RestaAvanzado();
        RA.setVisible(true);
    }//GEN-LAST:event_btnAvaActionPerformed

    private void btnPrincipianteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipianteMouseExited
        // TODO add your handling code here:
        btnPrincipiante.setBackground(Color.white);
    }//GEN-LAST:event_btnPrincipianteMouseExited

    private void btnInterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInterMouseEntered
        // TODO add your handling code here:
        btnInter.setBackground(Color.cyan);
    }//GEN-LAST:event_btnInterMouseEntered

    private void btnInterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInterMouseExited
        // TODO add your handling code here:
        btnInter.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnInterMouseExited

    private void btnAvaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvaMouseEntered
        // TODO add your handling code here:
        btnAva.setBackground(Color.cyan);
    }//GEN-LAST:event_btnAvaMouseEntered

    private void btnAvaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvaMouseExited
        // TODO add your handling code here:
        btnAva.setBackground(Color.white);
    }//GEN-LAST:event_btnAvaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DificultadResta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DificultadResta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DificultadResta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DificultadResta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DificultadResta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAva;
    private javax.swing.JButton btnInter;
    private javax.swing.JButton btnPrincipiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel perga;
    // End of variables declaration//GEN-END:variables
}
