/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomatematicassuma;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author lizar
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        fondo();
        this.setTitle("Bienvenido");
        diseñosBtn();
        String nombre = DatosAlumno.TxtFieldName.getText();
        jLabel2.setText(nombre);

        jPanel1.setBackground(Color.white);
        //this.setTitle("Selecciona la dificultad");
        imagen();

        LbFinn.setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
        //JOptionPane.showMessageDialog(null, "Bienvenido " + DatosAlumno.TxtFieldName.getText());

    }

    public void diseñosBtn() {
        btnSuma.setBackground(Color.white);
        btnResta.setBackground(Color.white);
        btnMulti.setBackground(Color.white);
        btnDivi.setBackground(Color.white);

    }

    public void imagen() {
        ImageIcon spidey = new ImageIcon(getClass().getResource("/Imagenes/finn.png"));
        Icon spiderman = new ImageIcon(spidey.getImage().getScaledInstance(LbFinn.getWidth(), LbFinn.getHeight(), Image.SCALE_DEFAULT));
        LbFinn.setIcon(spiderman);

    }
    
    public void fondo() {
        ImageIcon marq = new ImageIcon(getClass().getResource("/Imagenes/Pergamino.jpg"));
        Icon spiderman = new ImageIcon(marq.getImage().getScaledInstance(Pergamino2.getWidth(), Pergamino2.getHeight(), Image.SCALE_DEFAULT));
        Pergamino2.setIcon(spiderman);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbFinn = new javax.swing.JLabel();
        btnResta = new javax.swing.JButton();
        btnDivi = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Pergamino2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbFinn.setText("jLabel1");
        jPanel1.add(LbFinn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 120, 310, 450));

        btnResta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnResta.setText("RESTA");
        btnResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRestaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRestaMouseExited(evt);
            }
        });
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        jPanel1.add(btnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 136, 50));

        btnDivi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDivi.setText("DIVISIÓN");
        btnDivi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDiviMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDiviMouseExited(evt);
            }
        });
        btnDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiviActionPerformed(evt);
            }
        });
        jPanel1.add(btnDivi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 136, 50));

        btnSuma.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSuma.setText("SUMA");
        btnSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSumaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSumaMouseExited(evt);
            }
        });
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 136, 50));

        btnMulti.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMulti.setText("MULTIPLICACIÓN");
        btnMulti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMultiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMultiMouseExited(evt);
            }
        });
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });
        jPanel1.add(btnMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 136, 50));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("¡Bienvenido guerrer@!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 150, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Empieza tu aventura eligiendo un desafío");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 430, -1));

        Pergamino2.setText("jLabel4");
        jPanel1.add(Pergamino2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 540, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiviActionPerformed
        // TODO add your handling code here:
        Division Divi = new Division();
        Divi.setVisible(true);
    }//GEN-LAST:event_btnDiviActionPerformed

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        // TODO add your handling code here:
        DificultadMultiplicaciones a = new DificultadMultiplicaciones();
        a.setVisible(true);

    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
        DificultadSuma a = new DificultadSuma();
        a.setVisible(true);
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        // TODO add your handling code here:
        DificultadResta DR = new DificultadResta();
        DR.setVisible(true);
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnSumaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSumaMouseEntered
        // TODO add your handling code here:
        btnSuma.setBackground(Color.green);
    }//GEN-LAST:event_btnSumaMouseEntered

    private void btnSumaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSumaMouseExited
        // TODO add your handling code here:
        btnSuma.setBackground(Color.white);
    }//GEN-LAST:event_btnSumaMouseExited

    private void btnRestaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaMouseEntered
        // TODO add your handling code here:
        btnResta.setBackground(Color.green);
    }//GEN-LAST:event_btnRestaMouseEntered

    private void btnRestaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaMouseExited
        // TODO add your handling code here:
        btnResta.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnRestaMouseExited

    private void btnMultiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiMouseEntered
        // TODO add your handling code here:
        btnMulti.setBackground(Color.green);
    }//GEN-LAST:event_btnMultiMouseEntered

    private void btnMultiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiMouseExited
        // TODO add your handling code here:
        btnMulti.setBackground(Color.white);
    }//GEN-LAST:event_btnMultiMouseExited

    private void btnDiviMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiviMouseEntered
        // TODO add your handling code here:
        btnDivi.setBackground(Color.green);
    }//GEN-LAST:event_btnDiviMouseEntered

    private void btnDiviMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiviMouseExited
        // TODO add your handling code here:
         btnDivi.setBackground(Color.white);
    }//GEN-LAST:event_btnDiviMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbFinn;
    private javax.swing.JLabel Pergamino2;
    private javax.swing.JButton btnDivi;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnResta;
    public static javax.swing.JButton btnSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
