/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomatematicassuma;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author lizar
 */
public class RestaPrincipiante extends javax.swing.JFrame {

    /**
     * Creates new form RestaPrincipiante
     */
    public RestaPrincipiante() {
        initComponents();
        this.setTitle("Resta principiante");
        imagen();
        this.setLocationRelativeTo(null);
        this.btnRevisar.setBackground(Color.white);
        this.btnVolver.setBackground(Color.white);
        jPanel1.setBackground(Color.white);

        ImageIcon imagenCorrecto = new ImageIcon(getClass().getResource("/Imagenes/Palomita.png"));
        Icon fondo = new ImageIcon(imagenCorrecto.getImage().getScaledInstance(LbCorrect.getWidth(), LbCorrect.getHeight(), Image.SCALE_DEFAULT));
        //Pongo todos los labels a los que se va aplicar la propiedad

        //Visibilidad para labels correctos
        JLabel[] LbCorrectSetIcon = new JLabel[]{LbCorrect, LbCorrect1, LbCorrect2, LbCorrect3, LbCorrect4, LbCorrect5, LbCorrect6, LbCorrect7, LbCorrect8, LbCorrect9, LbCorrect10, LbCorrect11, LbCorrect12, LbCorrect13, LbCorrect14, LbCorrect15, LbCorrect16, LbCorrect17, LbCorrect18, LbCorrect19};
        for (JLabel labels : LbCorrectSetIcon) {
            labels.setIcon(fondo);
            labels.setVisible(false);
        }

        //Poniendo icono al label de incorrecto
        ImageIcon imagenIncorrecto = new ImageIcon(getClass().getResource("/Imagenes/tache.png")); //Se importa la dirección de la imagen
        Icon Fondo2 = new ImageIcon(imagenIncorrecto.getImage().getScaledInstance(LbIncorrect.getWidth(), LbIncorrect.getHeight(), Image.SCALE_DEFAULT));

        //Visibilidad para labels incorrectos
        JLabel[] LbIncorrectSet = new JLabel[]{LbIncorrect, LbIncorrect1, LbIncorrect2, LbIncorrect3, LbIncorrect4, LbIncorrect5, LbIncorrect6, LbIncorrect7, LbIncorrect8, LbIncorrect9, LbIncorrect10, LbIncorrect11, LbIncorrect12, LbIncorrect13, LbIncorrect14, LbIncorrect15, LbIncorrect16, LbIncorrect17, LbIncorrect18, LbIncorrect19};
        for (JLabel labels : LbIncorrectSet) {
            labels.setIcon(Fondo2);
            labels.setVisible(false);

        }

    }

    public void imagen() {
//Foto de resta

        ImageIcon marcoo = new ImageIcon(getClass().getResource("/Imagenes/marco3.gif"));

        Icon marquito = new ImageIcon(marcoo.getImage().getScaledInstance(marco.getWidth(), marco.getHeight(), Image.SCALE_DEFAULT));

        marco.setIcon(marquito);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbIncorrect10 = new javax.swing.JLabel();
        LbCorrect10 = new javax.swing.JLabel();
        TxtOp11 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        LbIncorrect11 = new javax.swing.JLabel();
        LbCorrect11 = new javax.swing.JLabel();
        TxtOp12 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        LbIncorrect12 = new javax.swing.JLabel();
        LbCorrect12 = new javax.swing.JLabel();
        TxtOp13 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        LbIncorrect13 = new javax.swing.JLabel();
        LbCorrect13 = new javax.swing.JLabel();
        TxtOp14 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        LbIncorrect14 = new javax.swing.JLabel();
        LbCorrect14 = new javax.swing.JLabel();
        TxtOp15 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        LbIncorrect15 = new javax.swing.JLabel();
        LbCorrect15 = new javax.swing.JLabel();
        TxtOp16 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        LbIncorrect16 = new javax.swing.JLabel();
        LbCorrect16 = new javax.swing.JLabel();
        TxtOp17 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        LbIncorrect17 = new javax.swing.JLabel();
        LbCorrect17 = new javax.swing.JLabel();
        TxtOp18 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        LbIncorrect19 = new javax.swing.JLabel();
        LbCorrect19 = new javax.swing.JLabel();
        TxtOp20 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        LbIncorrect18 = new javax.swing.JLabel();
        LbCorrect18 = new javax.swing.JLabel();
        TxtOp19 = new javax.swing.JTextField();
        LbIncorrect1 = new javax.swing.JLabel();
        LbCorrect1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtOp1 = new javax.swing.JTextField();
        LbCorrect = new javax.swing.JLabel();
        LbIncorrect = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtOp2 = new javax.swing.JTextField();
        TxtOp3 = new javax.swing.JTextField();
        TxtOp4 = new javax.swing.JTextField();
        TxtOp5 = new javax.swing.JTextField();
        TxtOp6 = new javax.swing.JTextField();
        TxtOp7 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LbCorrect2 = new javax.swing.JLabel();
        LbIncorrect2 = new javax.swing.JLabel();
        LbIncorrect3 = new javax.swing.JLabel();
        LbCorrect3 = new javax.swing.JLabel();
        LbIncorrect4 = new javax.swing.JLabel();
        LbCorrect4 = new javax.swing.JLabel();
        LbIncorrect5 = new javax.swing.JLabel();
        LbCorrect5 = new javax.swing.JLabel();
        LbIncorrect6 = new javax.swing.JLabel();
        LbCorrect6 = new javax.swing.JLabel();
        LbIncorrect7 = new javax.swing.JLabel();
        LbCorrect7 = new javax.swing.JLabel();
        TxtOp8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        LbIncorrect8 = new javax.swing.JLabel();
        LbCorrect8 = new javax.swing.JLabel();
        TxtOp9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        LbIncorrect9 = new javax.swing.JLabel();
        LbCorrect9 = new javax.swing.JLabel();
        TxtOp10 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnRevisar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        marco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbIncorrect10.setText("jLabel2");
        jPanel1.add(LbIncorrect10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 30, 32));

        LbCorrect10.setText("jLabel2");
        jPanel1.add(LbCorrect10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 30, 32));

        TxtOp11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp11ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 81, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("73 - 22");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        LbIncorrect11.setText("jLabel2");
        jPanel1.add(LbIncorrect11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 30, 32));

        LbCorrect11.setText("jLabel2");
        jPanel1.add(LbCorrect11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 30, 32));

        TxtOp12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp12ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 81, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("93 - 51");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        LbIncorrect12.setText("jLabel2");
        jPanel1.add(LbIncorrect12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 30, 32));

        LbCorrect12.setText("jLabel2");
        jPanel1.add(LbCorrect12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 30, 32));

        TxtOp13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp13ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 80, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("95 - 50");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));
        jPanel1.add(LbIncorrect13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 30, 32));
        jPanel1.add(LbCorrect13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 30, 32));

        TxtOp14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp14ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 81, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("47 - 3");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, -1));
        jPanel1.add(LbIncorrect14, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 30, 32));
        jPanel1.add(LbCorrect14, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 30, 32));

        TxtOp15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp15ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 81, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("91 - 40");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("68 - 52");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));
        jPanel1.add(LbIncorrect15, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 30, 32));
        jPanel1.add(LbCorrect15, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 30, 32));

        TxtOp16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp16ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 81, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setText("24 - 3");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));
        jPanel1.add(LbIncorrect16, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 30, 32));
        jPanel1.add(LbCorrect16, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 30, 32));

        TxtOp17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp17ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 81, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setText("35 - 14");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));
        jPanel1.add(LbIncorrect17, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 30, 32));
        jPanel1.add(LbCorrect17, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 30, 32));

        TxtOp18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp18ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 81, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setText("50 - 30");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));
        jPanel1.add(LbIncorrect19, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, 30, 32));
        jPanel1.add(LbCorrect19, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, 30, 32));

        TxtOp20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp20ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 81, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setText("88 - 57");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, -1, -1));
        jPanel1.add(LbIncorrect18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 30, 32));
        jPanel1.add(LbCorrect18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 30, 32));

        TxtOp19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp19ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp19, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 81, -1));

        LbIncorrect1.setText("jLabel2");
        jPanel1.add(LbIncorrect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 30, 32));

        LbCorrect1.setText("jLabel2");
        jPanel1.add(LbCorrect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 30, 32));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("68 - 63");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 56, -1));

        TxtOp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp1ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 78, -1));

        LbCorrect.setText("jLabel2");
        jPanel1.add(LbCorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 30, 32));

        LbIncorrect.setText("jLabel2");
        jPanel1.add(LbIncorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 30, 32));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("35 - 31");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));
        jPanel1.add(TxtOp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 81, -1));
        jPanel1.add(TxtOp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 81, -1));

        TxtOp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp4ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 81, -1));

        TxtOp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp5ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 81, -1));

        TxtOp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp6ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 81, -1));

        TxtOp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp7ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 81, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("47 - 17");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("57 - 6");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("24 - 4");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("40 - 20");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("72 - 51");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        LbCorrect2.setText("jLabel2");
        jPanel1.add(LbCorrect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 30, 32));

        LbIncorrect2.setText("jLabel2");
        jPanel1.add(LbIncorrect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 30, 32));

        LbIncorrect3.setText("jLabel2");
        jPanel1.add(LbIncorrect3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 30, 32));

        LbCorrect3.setText("jLabel2");
        jPanel1.add(LbCorrect3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 30, 32));

        LbIncorrect4.setText("jLabel2");
        jPanel1.add(LbIncorrect4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 30, 32));

        LbCorrect4.setText("jLabel2");
        jPanel1.add(LbCorrect4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 30, 32));

        LbIncorrect5.setText("jLabel2");
        jPanel1.add(LbIncorrect5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 30, 32));

        LbCorrect5.setText("jLabel2");
        jPanel1.add(LbCorrect5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 30, 32));

        LbIncorrect6.setText("jLabel2");
        jPanel1.add(LbIncorrect6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 30, 32));

        LbCorrect6.setText("jLabel2");
        jPanel1.add(LbCorrect6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 30, 32));

        LbIncorrect7.setText("jLabel2");
        jPanel1.add(LbIncorrect7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 30, 32));

        LbCorrect7.setText("jLabel2");
        jPanel1.add(LbCorrect7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 30, 32));

        TxtOp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp8ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 81, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("73 - 40");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        LbIncorrect8.setText("jLabel2");
        jPanel1.add(LbIncorrect8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 30, 32));

        LbCorrect8.setText("jLabel2");
        jPanel1.add(LbCorrect8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 30, 32));

        TxtOp9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp9ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 81, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("53 - 13");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        LbIncorrect9.setText("jLabel2");
        jPanel1.add(LbIncorrect9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 30, 32));

        LbCorrect9.setText("jLabel2");
        jPanel1.add(LbCorrect9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 30, 32));

        TxtOp10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOp10ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtOp10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 81, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("57 - 21");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        btnVolver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 150, 60));

        btnRevisar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRevisar.setText("Revisar");
        btnRevisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRevisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRevisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRevisarMouseExited(evt);
            }
        });
        btnRevisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRevisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 150, 60));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setText("Resuelve las restas y realiza el procedimiento en tu libreta");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 530, 30));

        marco.setText("jLabel21");
        jPanel1.add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 680));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtOp11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp11ActionPerformed

    private void TxtOp12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp12ActionPerformed

    private void TxtOp13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp13ActionPerformed

    private void TxtOp14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp14ActionPerformed

    private void TxtOp15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp15ActionPerformed

    private void TxtOp16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp16ActionPerformed

    private void TxtOp17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp17ActionPerformed

    private void TxtOp18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp18ActionPerformed

    private void TxtOp20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp20ActionPerformed

    private void TxtOp19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp19ActionPerformed

    private void TxtOp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp1ActionPerformed

    private void TxtOp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp4ActionPerformed

    private void TxtOp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp5ActionPerformed

    private void TxtOp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp6ActionPerformed

    private void TxtOp7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp7ActionPerformed

    private void TxtOp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp8ActionPerformed

    private void TxtOp9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp9ActionPerformed

    private void TxtOp10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOp10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOp10ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRevisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarMouseClicked
        //Ponemos un contador de clicks
    }//GEN-LAST:event_btnRevisarMouseClicked

    private void btnRevisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisarActionPerformed
        // TODO add your handling code here:

        String resultado1 = "5";
        String resultado2 = "4";
        String resultado3 = "51";
        String resultado4 = "30";
        String resultado5 = "20";
        String resultado6 = "21";
        String resultado7 = "20";

        String resultado8 = "33";
        String resultado9 = "40";
        String resultado10 = "36";
        String resultado11 = "51";
        String resultado12 = "42";
        String resultado13 = "45";
        String resultado14 = "44";

        String resultado15 = "51";
        String resultado16 = "16";
        String resultado17 = "21";
        String resultado18 = "21";
        String resultado19 = "31";
        String resultado20 = "20";

        if (TxtOp1.getText().equals(resultado1)) {
            LbCorrect.setVisible(true);
            LbIncorrect.setVisible(false);

        } else {
            LbIncorrect.setVisible(true);
            LbCorrect.setVisible(false);

        }
        //Segunda operacion
        if (TxtOp2.getText().equals(resultado2)) {
            LbCorrect1.setVisible(true);
            LbIncorrect1.setVisible(false);

        } else {
            LbIncorrect1.setVisible(true);
            LbCorrect1.setVisible(false);

        }
        //Tercera operacion
        if (TxtOp3.getText().equals(resultado3)) {
            LbCorrect2.setVisible(true);
            LbIncorrect2.setVisible(false);

        } else {
            LbIncorrect2.setVisible(true);
            LbCorrect2.setVisible(false);

        }

        //Cuarta operacion
        if (TxtOp4.getText().equals(resultado4)) {
            LbCorrect3.setVisible(true);
            LbIncorrect3.setVisible(false);

        } else {
            LbIncorrect3.setVisible(true);
            LbCorrect3.setVisible(false);

        }
        //Quinta operacion
        if (TxtOp5.getText().equals(resultado5)) {
            LbCorrect4.setVisible(true);
            LbIncorrect4.setVisible(false);

        } else {
            LbIncorrect4.setVisible(true);
            LbCorrect4.setVisible(false);

        }
        //Sexta operacion
        if (TxtOp6.getText().equals(resultado6)) {
            LbCorrect5.setVisible(true);
            LbIncorrect5.setVisible(false);

        } else {
            LbIncorrect5.setVisible(true);
            LbCorrect5.setVisible(false);

        }
        //Septima operacion
        if (TxtOp7.getText().equals(resultado7)) {
            LbCorrect6.setVisible(true);
            LbIncorrect6.setVisible(false);

        } else {
            LbIncorrect6.setVisible(true);
            LbCorrect6.setVisible(false);

        }
        //Octava operacion
        if (TxtOp8.getText().equals(resultado8)) {
            LbCorrect7.setVisible(true);
            LbIncorrect7.setVisible(false);

        } else {
            LbIncorrect7.setVisible(true);
            LbCorrect7.setVisible(false);

        }
        //Novena operacion
        if (TxtOp9.getText().equals(resultado9)) {
            LbCorrect8.setVisible(true);
            LbIncorrect8.setVisible(false);

        } else {
            LbIncorrect8.setVisible(true);
            LbCorrect8.setVisible(false);

        }
        //Decima operacion
        if (TxtOp10.getText().equals(resultado10)) {
            LbCorrect9.setVisible(true);
            LbIncorrect9.setVisible(false);

        } else {
            LbIncorrect9.setVisible(true);
            LbCorrect9.setVisible(false);

        }
        //11 operacion
        if (TxtOp11.getText().equals(resultado11)) {
            LbCorrect10.setVisible(true);
            LbIncorrect10.setVisible(false);

        } else {
            LbIncorrect10.setVisible(true);
            LbCorrect10.setVisible(false);

        }
        //12 operacion
        if (TxtOp12.getText().equals(resultado12)) {
            LbCorrect11.setVisible(true);
            LbIncorrect11.setVisible(false);

        } else {
            LbIncorrect11.setVisible(true);
            LbCorrect11.setVisible(false);

        }

        //13 operacion
        if (TxtOp13.getText().equals(resultado13)) {
            LbCorrect12.setVisible(true);
            LbIncorrect12.setVisible(false);

        } else {
            LbIncorrect12.setVisible(true);
            LbCorrect12.setVisible(false);

        }

        //14 operacion
        if (TxtOp14.getText().equals(resultado14)) {
            LbCorrect13.setVisible(true);
            LbIncorrect13.setVisible(false);

        } else {
            LbIncorrect13.setVisible(true);
            LbCorrect13.setVisible(false);

        }
        //15 operacion
        if (TxtOp15.getText().equals(resultado15)) {
            LbCorrect14.setVisible(true);
            LbIncorrect14.setVisible(false);

        } else {
            LbIncorrect14.setVisible(true);
            LbCorrect14.setVisible(false);

        }
        //16 operacion
        if (TxtOp16.getText().equals(resultado16)) {
            LbCorrect15.setVisible(true);
            LbIncorrect15.setVisible(false);

        } else {
            LbIncorrect15.setVisible(true);
            LbCorrect15.setVisible(false);

        }
        //17 operacion
        if (TxtOp17.getText().equals(resultado17)) {
            LbCorrect16.setVisible(true);
            LbIncorrect16.setVisible(false);

        } else {
            LbIncorrect16.setVisible(true);
            LbCorrect16.setVisible(false);

        }
        //18 operacion
        if (TxtOp18.getText().equals(resultado18)) {
            LbCorrect17.setVisible(true);
            LbIncorrect17.setVisible(false);

        } else {
            LbIncorrect17.setVisible(true);
            LbCorrect17.setVisible(false);

        }
        //19 operacion
        if (TxtOp19.getText().equals(resultado19)) {
            LbCorrect18.setVisible(true);
            LbIncorrect18.setVisible(false);

        } else {
            LbIncorrect18.setVisible(true);
            LbCorrect18.setVisible(false);

        }
        //20 operacion
        if (TxtOp20.getText().equals(resultado20)) {
            LbCorrect19.setVisible(true);
            LbIncorrect19.setVisible(false);

        } else {
            LbIncorrect19.setVisible(true);
            LbCorrect19.setVisible(false);

        }


    }//GEN-LAST:event_btnRevisarActionPerformed

    private void btnRevisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarMouseEntered
        // TODO add your handling code here:
        btnRevisar.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnRevisarMouseEntered

    private void btnRevisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarMouseExited
        btnRevisar.setBackground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevisarMouseExited

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        // TODO add your handling code here:
        btnVolver.setBackground(Color.RED);
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited

        btnVolver.setBackground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaPrincipiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbCorrect;
    private javax.swing.JLabel LbCorrect1;
    private javax.swing.JLabel LbCorrect10;
    private javax.swing.JLabel LbCorrect11;
    private javax.swing.JLabel LbCorrect12;
    private javax.swing.JLabel LbCorrect13;
    private javax.swing.JLabel LbCorrect14;
    private javax.swing.JLabel LbCorrect15;
    private javax.swing.JLabel LbCorrect16;
    private javax.swing.JLabel LbCorrect17;
    private javax.swing.JLabel LbCorrect18;
    private javax.swing.JLabel LbCorrect19;
    private javax.swing.JLabel LbCorrect2;
    private javax.swing.JLabel LbCorrect3;
    private javax.swing.JLabel LbCorrect4;
    private javax.swing.JLabel LbCorrect5;
    private javax.swing.JLabel LbCorrect6;
    private javax.swing.JLabel LbCorrect7;
    private javax.swing.JLabel LbCorrect8;
    private javax.swing.JLabel LbCorrect9;
    private javax.swing.JLabel LbIncorrect;
    private javax.swing.JLabel LbIncorrect1;
    private javax.swing.JLabel LbIncorrect10;
    private javax.swing.JLabel LbIncorrect11;
    private javax.swing.JLabel LbIncorrect12;
    private javax.swing.JLabel LbIncorrect13;
    private javax.swing.JLabel LbIncorrect14;
    private javax.swing.JLabel LbIncorrect15;
    private javax.swing.JLabel LbIncorrect16;
    private javax.swing.JLabel LbIncorrect17;
    private javax.swing.JLabel LbIncorrect18;
    private javax.swing.JLabel LbIncorrect19;
    private javax.swing.JLabel LbIncorrect2;
    private javax.swing.JLabel LbIncorrect3;
    private javax.swing.JLabel LbIncorrect4;
    private javax.swing.JLabel LbIncorrect5;
    private javax.swing.JLabel LbIncorrect6;
    private javax.swing.JLabel LbIncorrect7;
    private javax.swing.JLabel LbIncorrect8;
    private javax.swing.JLabel LbIncorrect9;
    public static javax.swing.JTextField TxtOp1;
    public static javax.swing.JTextField TxtOp10;
    public static javax.swing.JTextField TxtOp11;
    public static javax.swing.JTextField TxtOp12;
    public static javax.swing.JTextField TxtOp13;
    public static javax.swing.JTextField TxtOp14;
    public static javax.swing.JTextField TxtOp15;
    public static javax.swing.JTextField TxtOp16;
    public static javax.swing.JTextField TxtOp17;
    public static javax.swing.JTextField TxtOp18;
    public static javax.swing.JTextField TxtOp19;
    public static javax.swing.JTextField TxtOp2;
    public static javax.swing.JTextField TxtOp20;
    public static javax.swing.JTextField TxtOp3;
    public static javax.swing.JTextField TxtOp4;
    public static javax.swing.JTextField TxtOp5;
    public static javax.swing.JTextField TxtOp6;
    public static javax.swing.JTextField TxtOp7;
    public static javax.swing.JTextField TxtOp8;
    public static javax.swing.JTextField TxtOp9;
    private javax.swing.JButton btnRevisar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel marco;
    // End of variables declaration//GEN-END:variables
}
